### ISSUE TITLE
Sidebar background manager closed

### ISSUE THREAD

**Issue by ersa3772** [creativetimofficial/ct-now-ui-dashboard-pro-react#11]
The background manager theme we have downloaded is also closed.

online theme visible
![image](https://user-images.githubusercontent.com/40817984/42259347-c3fae3f4-7f68-11e8-9e9a-d6be319667ef.png)

download my theme  note visible
![image](https://user-images.githubusercontent.com/40817984/42259391-e7f8fe80-7f68-11e8-844a-b08ce1a573fd.png)

**Comment by einazare** [comment]
Hello @ersa3772,

And thank you for your interest in using our product.
That is a dropdown menu created just for demo purposes, i.e. to show our clients/users how the sidebar can look on different colors, and also, if they do not see the minimize button, how the sidebar looks minimized.
To create that dropdown it is fairly easy for someone who knows how to juggle with props (function props) that change from child node the parent.
Here are some links about this functionality in react: 

- [https://stackoverflow.com/questions/35537229/how-to-update-parents-state-in-react](https://stackoverflow.com/questions/35537229/how-to-update-parents-state-in-react)
- [https://ourcodeworld.com/articles/read/409/how-to-update-parent-state-from-child-component-in-react](https://ourcodeworld.com/articles/read/409/how-to-update-parent-state-from-child-component-in-react)
- [https://medium.com/@kyledavelaar/updating-parent-component-state-from-children-components-in-react-2ead9b9cec9f](https://medium.com/@kyledavelaar/updating-parent-component-state-from-children-components-in-react-2ead9b9cec9f)

Best,
Manu
