### ISSUE TITLE
Pro Version

### ISSUE THREAD

**Issue by ersa3772** [creativetimofficial/ct-now-ui-dashboard-pro-react#12]
Hi,
We have purchased the PRO version and we supposed to have 160 components as you wrote in below link, but instead we have only 7 components in examples folder.

https://www.creative-tim.com/product/now-ui-dashboard-pro?coupon=30happy-4th-july&ref=4th-July

Regards

**Comment by einazare** [comment]
Hello @ersa3772 ,

And thank you for your interest in using our product.
I believe that you haven't downloaded the right product. Please check again (you should have 18 folders inside the components folder).

Best,
Manu
