### ISSUE TITLE
Form Wizard Finsh Button.

### ISSUE THREAD

**Issue by jamalabo1** [creativetimofficial/ct-now-ui-dashboard-pro-react#14]
Hello, 
 
1)  css file is blocking finsh button in Form Wizard,
2) how can i control finsh button click ? `onClick`

**Comment by einazare** [comment]
Hello @jamalabo1 ,

And thank you for your interest in using our product.
For the first one, i am going to make some changes this week - we've decided to update this product.
The second one, i think you need to be a bit more specific. I really do not understand the question.

Best,
Manu

**Comment by jamalabo1** [comment]
@EINazare after removing the line that makes the button disapper, the finsh button shows, 
how can i make event listener (onClick)

**Comment by einazare** [comment]
Hello again @jamalabo1 ,

Does this link help you: [https://github.com/creativetimofficial/react-bootstrap-wizard#readme](https://github.com/creativetimofficial/react-bootstrap-wizard#readme) ?

Best,
Manu

**Comment by jamalabo1** [comment]
@EINazare 
i know it has been long time since this issue but `finishButtonClick` is not triggered

## EDIT 
only triggered when validate is on!

**Comment by einazare** [comment]
Hello again, @jamalabo1 ,

I'll make an update to the react-bootstrap-wizard to fix this issue.

Best,
Manu
