### ISSUE TITLE
Input-Group-Prepend

### ISSUE THREAD

**Issue by shezankazi** [creativetimofficial/ct-now-ui-dashboard-pro-react#15]
It seems in a recent bootstrap update `input-group-addon` was replaced by `input-group-prepend` and `input-group-apend`.

Can you please add this to your scss?

**Comment by einazare** [comment]
Hello @shezankazi ,

And thank you for your interest in using our product.
We are going to make an update to this product - as of moment it is on bootstrap 4 beta.
The update is going to be started today, and i hope it will be done in a few days, maybe even tomorrow.

Best,
Manu
