### ISSUE TITLE
Change logo

### ISSUE THREAD

**Issue by sergioadonis** [creativetimofficial/ct-now-ui-dashboard-pro-react#16]
# How can I change the react logo in the sidebar?

**Comment by einazare** [comment]
Hello there @sergioadonis ,

Thank you for your interest in working with our products.
To change the logo from the Sidebar you need to navigate inside: `src/components/Sidebar/Sidebar.jsx`.
Here, on line 12 you will see this line: `import logo from "logo-white.svg";`. This is the line where we import the React Logo. And after this, at line 81 you will see this `<img src={logo} alt="react-logo" />`. Here we render the React Logo as an image.
So, here you should change the logo.

Hope this information helps. If you have any further questions, please let us know.

Best,
Manu
