### ISSUE TITLE
Statics in built index.html are referenced with wrong path

### ISSUE THREAD

**Issue by jcapogna** [creativetimofficial/ct-now-ui-dashboard-pro-react#18]
# Expected Behavior

The built index.html correctly references the built statics. 

# Current Behavior

The paths in the index.html are prefixed with "now-ui-dashboard-pro-react", which is not part of the build static directory structure. 

For example

- index.html references /now-ui-dashboard-pro-react/static/js/main.f78b451e.js
- but this file exists at /static/js/main.f78b451e.js

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Download this template
2. Run 'npm run build'
3. Either observe the built files or try to load the built files via a server

## Context

Out of the box setup

**Comment by jcapogna** [comment]
This is a simple fix. I just needed to change the homepage property in package.json to either my full URI or "./ to get relative URLs. I prefer the latter option since it works in all environments (dev and production)

**Comment by einazare** [comment]
Hello there @jcapogna ,

Thank you for your interest in working with our products and sorry for not being able to come to your help.
Glad that everything works fine.

Best,
Manu
