### ISSUE TITLE
React Big Calendar's 'Day View' and 'Week View' events are not spanning to the correct end time

### ISSUE THREAD

**Issue by kunaljaypatel** [creativetimofficial/ct-now-ui-dashboard-pro-react#19]
!!! IF YOU DO NOT USE THIS ISSUES TEAMPLATE, YOUR ISSUE IS LIABLE TO BEING IGNORED BY US

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [yes ] I am running the latest version
- [yes ] I checked the documentation and found no answer
- [yes ] I checked to make sure that this issue has not already been filed
- [yes ] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

React Big Calendar's 'Day View' and 'Week View' events should span to the correct end time.

# Current Behavior

They are only spanning a small block. I've looked through the react-big-calendar documentation, and I haven't been able to find someone with a similar issue. 

I have attached two screenshots for [reference](https://imgur.com/a/Hm8ykOi) comparing the expected behavior to the current behavior. The expected behavior is from the React-Big-Calendar's website. 

# Failure Information (for bugs)

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. go to Creative Tim's example [website for Now-UI-Dashboard-Pro-React](https://demos.creative-tim.com/now-ui-dashboard-pro-react/#/calendar)
2. Click Week view and look for an event called "Birthday Party" or "Lunch"  
3. Observe how the calendar cells are not spanning correctly to the correct end times.

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Device: Macbook Pro 
* Operating System: Mac OS
* Browser and Version: Safari Version 12.0.2

## Failure Logs

N/A

**Comment by einazare** [comment]
Hello there @kunaljaypatel ,

Thank you for your interest in working with our products.
Go inside `src/assets/scss/now-ui-dashboard/plugins/_plugin-react-big-calendar.scss`, and delete lines 654 and 655:
```
height: unset !important;
  max-height: unset !important;
```

Best,
Manu
