### ISSUE TITLE
Chart image issue

### ISSUE THREAD

**Issue by bbogly** [creativetimofficial/ct-now-ui-dashboard-pro-react#20]
!!! IF YOU DO NOT USE THIS ISSUES TEAMPLATE, YOUR ISSUE IS LIABLE TO BEING IGNORED BY US

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [V] I am running the latest version
- [V] I checked the documentation and found no answer
- [V] I checked to make sure that this issue has not already been filed
- [V] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Normally display chart image

# Current Behavior

Wrong chart image

# Failure Information (for bugs)

As a screenshot

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Scroll it to down

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Device: iMac
* Operating System: 10.14.1 (18B75)
* Browser and Version: Chrome Version 71.0.3578.98 (Official Build) (64-bit)

## Failure Logs

--
![screen shot 2018-12-30 at 1 00 50 pm](https://user-images.githubusercontent.com/4445622/50544283-abff2000-0c33-11e9-9d3b-ced6b5e2fb4b.png)

**Comment by einazare** [comment]
Hello there @monoie ,

Thank you for your interest in working with our products.
Can you provide some more information?
```
# Expected Behavior

Normally display chart image
```
I do not think you are using our charts the right way.
```
# Current Behavior

Wrong chart image
```
What image should be instead of the attached one? 
```
# Failure Information (for bugs)

As a screenshot
```
I can clearly see something wrong in the screenshot you've provided, but how did that happen?
```
## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Scroll it to down
```
What should I scroll down?

Best,
Manu

**Comment by einazare** [comment]
Accidentally closed the issue.

**Comment by bbogly** [comment]
> Hello there @monoie ,
> 
> Thank you for your interest in working with our products.
> Can you provide some more information?
> 
> ```
> # Expected Behavior
> 
> Normally display chart image
> ```
> I do not think you are using our charts the right way.
> 
> ```
> # Current Behavior
> 
> Wrong chart image
> ```
> What image should be instead of the attached one?
> 
> ```
> # Failure Information (for bugs)
> 
> As a screenshot
> ```
> I can clearly see something wrong in the screenshot you've provided, but how did that happen?
> 
> ```
> ## Steps to Reproduce
> 
> Please provide detailed steps for reproducing the issue.
> 
> 1. Scroll it to down
> ```
> What should I scroll down?
> 
> Best,
> Manu

Just scroll wheel

**Comment by einazare** [comment]
Hello again, @monoie ,

Please give us a detailed step by step guide.
What wheel to scroll?
Where to scroll that wheel?

Best,
Manu

**Comment by bbogly** [comment]
just mouse wheel

2019년 1월 14일 (월) 오후 7:20에 Nazare Emanuel-Ioan <notifications@github.com>님이
작성:

**Comment by einazare** [comment]
Hello again, @monoie ,

Discussed your issue with my colleagues and we do not understand what the issue is.
Can you please send a copy of your code on my email: manu@creative-tim.com ?

Best,
Manu
