### ISSUE TITLE
This is incompatible with IE8

### ISSUE THREAD

**Issue by Yakovtam** [creativetimofficial/ct-now-ui-dashboard-pro-react#22]
This is incompatible with IE8，Please ！ I really want to buy it.

**Comment by Yakovtam** [comment]
![11903b67142beefd95ebd98185a032f](https://user-images.githubusercontent.com/23466613/55570279-adaa1980-5735-11e9-92e6-15250a21984c.png)

**Comment by Yakovtam** [comment]
If you are IE8 compatible, I would like to pay 100 for it

**Comment by Yakovtam** [comment]
If you are IE8 compatible, I would like to pay $100 for it

**Comment by einazare** [comment]
Hello there, @Yakovtam ,

Thank you for your interest in working with our products.
Unfortunately, we do not offer support for any IE versions.
We only offer support for the latest 2 versions of Edge.
You can check our browser compatibility here: https://github.com/creativetimofficial/ct-now-ui-dashboard-pro-react#browser-support

Best,
Manu
