### ISSUE TITLE
Import the product to create-react-app project

### ISSUE THREAD

**Issue by shekharkc** [creativetimofficial/ct-now-ui-dashboard-pro-react#24]
!!! IF YOU DO NOT USE THIS ISSUES TEAMPLATE, YOUR ISSUE IS LIABLE TO BEING IGNORED BY US

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version - Yes
- [x] I checked the documentation and found no answer - Yes
- [x] I checked to make sure that this issue has not already been filed - Yes
- [x] I'm reporting the issue to the correct repository (for multi-repository projects) - Yes

# Expected Behavior

Detailed documentation to import the project into create-react-app could have been provided.

Please describe the behaviour you are expecting

The documentation, especially with respect to (optional) installation with create-react-app could be enhanced to assist newbies starting with React projects.
----------------------

Hi, 

Thank you for creating these wonderful products.

Needed a bit of clarification on importing the Product into a project created using create-react-app (the optional part mentioned in the documentation). Any documentation with respect to the same as apparently the project created with create-react-app doesn't permit import of files/ folders/ modules outside its src directory?

Apologies if this is too trivial a question.

Best regards

**Comment by einazare** [comment]
Hello again, @shekharkc ,

As one of our clients put it very correctly, when you already have a project started, and you want to add our product on top of that, you just need to copy all of our styles, and then copy the components that you would like inside your project.
Here is a link to that comment: https://github.com/creativetimofficial/ct-material-dashboard-pro-react/issues/50#issuecomment-407030675

Hope this was of help. Let me know if you have further questions.

Best,
Manu

**Comment by shekharkc** [comment]
Many thanks. Shall try to do that and get back to you if there are any issues.
Would the team at creative-Tim consider adding these steps in the documentation? Shall be of immense help to newbies with React. Or, perhaps may be a small script to do that?

Thanks

**Comment by einazare** [comment]
Hello again @shekharkc ,

You can take a look at these tutorials:
https://medium.freecodecamp.org/how-to-use-reactjs-with-webpack-4-babel-7-and-material-design-ff754586f618
https://medium.freecodecamp.org/how-to-use-redux-in-reactjs-with-real-life-examples-687ab4441b85
https://medium.freecodecamp.org/how-to-connect-a-react-design-system-with-firebase-and-redux-9646ca1c733f

Best,
Manu

**Comment by shekharkc** [comment]
Thank you very much. Had a look at the tutorials shared by you. Very relevant to what I have in mind. Shall try out the steps listed in them. 
On the other hand, I tried the following:-
1.  Updated dependencies in my create-react-app to those required by the now-ui-dashboard-react product.
2. Copied the contents of src folder in now-ui-dashboard-react to my project src folder.
Much similar to what your article (the first one) mentions and what the link you shared describes: creativetimofficial/ct-material-dashboard-pro-react#50 (comment) 

However, the app breaks and wouldn't compile. Still trying to figure out what could have gone wrong. 

Wonder what the author at comment#50 means when he says **_import them like it was an npm package_** - "If you're planning to integrate it in a project that already exists you create two directories named /components and /assets under /src and **import them like it was an npm package**, and this is all you might need" . 

IMHO, it will be nice if creative-Tim includes steps for importing their products into client apps in the documentation as I figure this is more likely to be the common use case. Highly likely that your product will be imported/ referenced by the client app than the other way around.

Thank you & Best

**Comment by einazare** [comment]
Hello again, @shekharkc ,

The errors might appear from the fact that we use absolute paths inside our product.
This means we do not import like: `import X from "../../../../../../X";` we import it something like `import X from x/y/z/t/X";`. For this to work please take a look at our live docs here: https://demos.creative-tim.com/now-ui-dashboard-pro-react/#/documentation/tutorial . 

Best, 
Manu

**Comment by shekharkc** [comment]
Thank you very much. Have been able to do the needful.
But, again - it's kind of a hack. Would still recommend including the steps as part of your standard documentation for the reasons mentioned above. Of course, your call.

Best
