### ISSUE TITLE
Redownload pro but get free version

### ISSUE THREAD

**Issue by hbinduni** [creativetimofficial/ct-now-ui-dashboard-pro-react#26]
Hi, i try to redownload my package from my purchase because i saw the update a few days ago.  It suppose to be pro version but instead i got free version package. Can you check? 

I got the file `now-ui-dashboard-pro-react-v1.3.0.zip` but it only have this folder, very different with my previous pro version:

The same happen with this i think, [Pro Version issue](https://github.com/creativetimofficial/ct-now-ui-dashboard-pro-react/issues/12)

<img width="422" alt="Screen Shot 2019-07-13 at 03 08 21" src="https://user-images.githubusercontent.com/1378410/61155592-7e1c6180-a51b-11e9-88af-fc6a3c714914.png">

**Comment by einazare** [comment]
Hello there, @hbinduni ,

Thank you for your interest in working with our products.
Why haven't you used our issue template:
```
<!--
 IMPORTANT: Please use the following link to create a new issue:

  https://www.creative-tim.com/new-issue/now-ui-dashboard-pro-react

**If your issue was not created using the app above, it will be closed immediately.**
-->

<!--
Love Creative Tim? Do you need Angular, React, Vuejs or HTML? You can visit:
👉  https://www.creative-tim.com/bundles
👉  https://www.creative-tim.com
-->
```

The problem was just solved, but please next time follow our rules.

Best,
Manu

**Comment by hbinduni** [comment]
Thank you for your response
