### ISSUE TITLE
change sidebar nav background

### ISSUE THREAD

**Issue by seanconnelly34** [creativetimofficial/ct-now-ui-dashboard-pro-react#29]
Hi there,

I have purchased this dashboard 
https://www.creative-tim.com/product/now-ui-dashboard-pro-react

How am I able to change the background of the sidebar nav to a gradient background? 

As well, after editing the file "now-ui-dashboard.css" the changes are not being reflected. I attempted to change the active link color on the sidebar nav, but it is not being reflected.

Thanks,

**Comment by einazare** [comment]
Hello there, @seanconnelly34 ,

Thank you for your interest in working with our products.
May I ask you why did you not follow our rules of opening a new Github Issue?:
```
<!--
 IMPORTANT: Please use the following link to create a new issue:

  https://www.creative-tim.com/new-issue/now-ui-dashboard-pro-react

**If your issue was not created using the app above, it will be closed immediately.**
-->

<!--
Love Creative Tim? Do you need Angular, React, Vuejs or HTML? You can visit:
👉  https://www.creative-tim.com/bundles
👉  https://www.creative-tim.com
-->
```
For your issue you can do the following:

1. Create a new css file.
2. Import the new css file after our styles inside src/index (line 25)
3. Add the following code inside the new css file:
```
.off-canvas-sidebar:after, .sidebar:after{
  background: linear-gradient(#e66465, #9198e5) !important;
}
```
!NOTE: the above code is just a sample, you should change `linear-gradient(#e66465, #9198e5)` with the desired colors.

Best,
Manu
