### ISSUE TITLE
Datatable defaults config bug 

### ISSUE THREAD

**Issue by senorcodecat** [creativetimofficial/ct-now-ui-dashboard-pro-react#3]
Getting the following error after compiling (no changes, just downloaded, ran npm install, npm start)
```
TypeError: Cannot read property 'defaults' of undefined

```(anonymous function)
C:/Users/corey/Documents/TOP/client/EXPERIMENTAL/now-ui-dashboard-pro-react-v1.0.0/node_modules/datatables.net-bs/js/dataTables.bootstrap.js:47
  44 | 
  45 | 
  46 | /* Set the defaults for DataTables initialisation */
> 47 | $.extend( true, DataTable.defaults, {
  48 | 	dom:
  49 | 		"<'row'<'col-sm-6'l><'col-sm-6'f>>" +
  50 | 		"<'row'<'col-sm-12'tr>>" +```

**Comment by einazare** [comment]
Hello @senorcodecat ,

Thank you for your interest in using our product.
I've made a quick search on the internet and found out that before you initialize the DataTable, you need to set it's defaults, so you should put in `src/views/Tables/DataTables.jsx`, inside the `componentDidMount()` function, before the initialization of the DataTable (line 20) the following code:
```
$.extend( true, $.fn.dataTable.defaults, {
    "searching": true,
    "ordering": true
} );
```
You can find more about this at the following link: [https://datatables.net/examples/advanced_init/defaults.html](https://datatables.net/examples/advanced_init/defaults.html)

Waiting for your response to see if everything is fine.

Best,
Manu

**Comment by einazare** [comment]
Hello @senorcodecat ,

Is it ok if i close this issue?
Is DataTables working now?

Best,
Manu
