### ISSUE TITLE
[Bug] Demo not working on IE11

### ISSUE THREAD

**Issue by charles-dejager** [creativetimofficial/ct-now-ui-dashboard-pro-react#30]
### Version
1.2.0
### Reproduction link
https://demos.creative-tim.com/now-ui-dashboard-pro-react/#/admin/dashboard
### Operating System
Windows
### Device
Windows
### Browser & Version
IE 11
### Steps to reproduce
Open the demo on IE11
### What is expected?
Should show the dashboard
### What is actually happening?
When opening the demo version it fails to load on IE11 with an error
SCRIPT438: Object doesn't support property or method 'assign'
forwardRef.js

---
### Additional comments
I am using this template for my own application and cannot get it to work on IE11.

**Comment by einazare** [comment]
Hello there, @charles-dejager ,

Thank you for your interest in working with our products.
We do not offer support for any Internet Explorer version, please check our README here: https://github.com/creativetimofficial/ct-now-ui-dashboard-pro-react#browser-support

Best,
Manu

**Comment by charles-dejager** [comment]
According to your website you do support IE

**Comment by einazare** [comment]
Hello again, @charles-dejager ,

Can you please point me to where you have read that? That is a typo, or it is something old from 5 years ago.

Best,
Manu

**Comment by charles-dejager** [comment]
That is the readme that you pointed me to. There is an icon for IE.

**Comment by einazare** [comment]
Hello again, @charles-dejager 

Please note that the logo for IE and the logo for Edge are different, here is the IE logo: https://en.wikipedia.org/wiki/Internet_Explorer#/media/File:Internet_Explorer_9_icon.svg 
And here is the Edge logo: https://en.wikipedia.org/wiki/Microsoft_Edge#/media/File:Microsoft_Edge_logo.svg, if this not clear enough, I will refer to my first response, we do not offer support for Internet Explorer, only for Microsoft Edge. 
I will forward your question to my superiors to see how we can make our README a bit less confusing about Edge and Explorer. 

Best, 
Manu

**Comment by charles-dejager** [comment]
Thanks for the clarification
