### ISSUE TITLE
[Bug] Deprecated dependencies and high vulnerabilities

### ISSUE THREAD

**Issue by nurmikko** [creativetimofficial/ct-now-ui-dashboard-pro-react#35]
### Version
1.4.0
### Reproduction link
https://demos.creative-tim.com/now-ui-dashboard-pro-react
### Operating System
any
### Device
any
### Browser & Version
any
### Steps to reproduce
There are many deprecated dependencies and at the moment 10 high-level vulnerabilities. When can we expect update for the product?
### What is expected?
-
### What is actually happening?
-

---

**Comment by einazare** [comment]
Hello there, @nurmikko ,

We'll make an update in the following few months.

Best,
Manu
