### ISSUE TITLE
Mixins may not be defined within control directives or other mixins.

### ISSUE THREAD

**Issue by kzeman** [creativetimofficial/ct-now-ui-dashboard-pro-react#4]
I have unpacked a file "now-ui-dashboard-pro-react-v1.0.0.zip" to the empty directory, npm install, npm start:

{
  "status": 1,
  "file": "C:/React/w/src/assets/scss/now-ui-dashboard/mixins/_badges.scss",
  "line": 12,
  "column": 12,
  "message": "Mixins may not be defined within control directives or other mixins.",
  "formatted": "Error: Mixins may not be defined within control directives or other mixins.\n        on line 12 of src/assets/scss/now-ui-dashboard/mixins/_badges.scss\n>>     @mixin badges-color($color){\n\n   -----------^\n"
}

**Comment by einazare** [comment]
Hello @kzeman ,

I've searched the internet for a solution to this issue, and found nothing to solve it.
This issue comes from the sass builder (from scss to css) we've been using on start/build so that we wouldn't have to build our css always.
A fix would be to change the scripts inside `package.json` so that the sass wouldn't be build every time. You would have to put this in the scripts:
```
"scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test --env=jsdom",
    "eject": "react-scripts eject"
  }
```
We are going to look further on this issue and maybe find a solution. On Mac everything works perfectly, but on Windows it seems that it doesn't work anymore.
If you make those changes, and wish to change our scss, you would have to compile the scss yourself.

Best,
Manu

**Comment by thecloudslayer** [comment]
The default npm start is not working on a mac. the work around script works for me on a mac.

**Comment by kzeman** [comment]
I have found, problem is node-sass library. Version 4.6.1 included within Tims project package.json works fine, but actuall version of node-sass library causes an error.

**Comment by einazare** [comment]
@kzeman ,

Thank you for your solve of this issue. We are going to add node-sass@4.6.1 as a dependencie in our product.

**Comment by thecloudslayer** [comment]
I have "node-sass-chokidar": "0.0.3",  it seems.

**Comment by thecloudslayer** [comment]
@kzeman can you share your package.json?

**Comment by gbourne1** [comment]
I install node-sass@4.6.1 and works. The current version of node-sass (4.8.3) doesn't work. You also need to have node-sass-chokidar@0.0.3 (latest version also breaks).

**Comment by asela-wijesinghe** [comment]
![image](https://user-images.githubusercontent.com/23404276/38302866-d339712a-3821-11e8-8f0c-fe8d012ea440.png)

i have both the dependencies but still the same error is thrown on yarn start,

![image](https://user-images.githubusercontent.com/23404276/38302908-f7c84a7a-3821-11e8-9f89-3c6fee4cdfd4.png)

**Comment by einazare** [comment]
Hello @asela-wijesinghe ,

Thank you for your interest in using our product.
Could you please delete the `node_modules` folder, and run again `npm install`, `npm start` ?

Best,
Manu

**Comment by asela-wijesinghe** [comment]
@EINazare i did that several times as well manu, and also

 1. i tried different versions of node-sass and node-sass-chokidar
 2. i tried 4.6.1 and 0.0.3 as well
 3 i tried ~4.6.1 and '~0.0.3'
 4.i tried on different node versions 8.10.0 and 6.9.1

but still couldn't start the template running with sass

**Comment by einazare** [comment]
@asela-wijesinghe, not sure what advice to give to you. For the moment you could work over our css file, or find another way to compile the scss and change back the scripts to the default from `create-react-app`
```
"scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test --env=jsdom",
    "eject": "react-scripts eject"
  }
```

Another thing would be to give me your project and see if i get the same error, and if not, maybe we could find what is different from my machine to yours.

**Comment by asela-wijesinghe** [comment]
@EINazare thanks i am doing that from few days now and using only CSS just tried to sort it out if possible

**Comment by einazare** [comment]
Hello guys, (@asela-wijesinghe , @gbourne1 , @thecloudslayer , @kzeman )

I found a fix for this issue (i am going to make and update in a few days with this fix):

- go in `src/assets/scss/now-ui-dashboard/mixins/_badges.scss`
- move `@mixin badges-color($color){...}` outside `@mixin create-colored-badges(){..}`

Best,
Manu
