### ISSUE TITLE
Tables not responsive

### ISSUE THREAD

**Issue by chichi13** [creativetimofficial/ct-now-ui-dashboard-pro-react#5]
Hello,

I discovered a problem with the tables. They're not responsive. On the computer everything is correct (https://prnt.sc/iw39j2). On the other hand on mobile (Iphone 7 resolution here) : https://prnt.sc/iw39ny Impossible to see "Office" "Position" "Age" and "Actions". Is this possible to fix it please ?

Best regards.

**Comment by einazare** [comment]
Hello @chichi13 ,

We've done some testing and on our devices everything works fine. 
Could you please tell us if you've changed something?
Or could you give us access to your repo, or if you could give us your archive to see if there is something different from what we have (my email is manu@creative-tim.com if you want to send your archive) ?

Best,
Manu

**Comment by chichi13** [comment]
Hello,

I rebuild the project, now the tables are responsive. Sorry for the inconvenience.

Best regards
