### ISSUE TITLE
Upgrade to Webpack 4.3.0

### ISSUE THREAD

**Issue by gbourne1** [creativetimofficial/ct-now-ui-dashboard-pro-react#7]
Webpack 3.8.1 work, but the latest version gives this error:

Cannot read property 'thisCompilation' of undefined
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nud-pro-react@1.0.0 start-js: `cross-env NODE_PATH=./src react-scripts start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nud-pro-react@1.0.0 start-js script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/everdome/.npm/_logs/2018-03-27T21_43_03_808Z-debug.log
ERROR: "start-js" exited with 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nud-pro-react@1.0.0 start: `npm-run-all -p watch-css start-js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nud-pro-react@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/everdome/.npm/_logs/2018-03-27T21_43_03_946Z-debug.log

**Comment by einazare** [comment]
Hello @gbourne1 

Thank you for your interest in our product and for sharing this with us.
In our dependencies we have webpack@3.8.1. After a quick search, this issue can be solved only by using webpack@3.x.x and not webpack@4.x.x. 
We are going to leave our dependencies as they already are, and we are going to watch the development of webpack, and see if this issue will be solved.

Best,
Manu
