### ISSUE TITLE
Scroll to top button

### ISSUE THREAD

**Issue by kzeman** [creativetimofficial/ct-now-ui-dashboard-pro-react#9]
Any ideas/help for scroll to top button?

**Comment by einazare** [comment]
Hello again @kzeman ,

Where would you put this button?
For example, if you would put it in the `src/layouts/Dashboard.jsx`, you could add the following code inside the `.wrapper` div at the beginning of the render method:
```
<Button 
       color="info" 
       style={{position: "absolute",left:"auto",right:"0",zIndex:"9999"}} 
       onClick={(e)=>this.refs.mainPanel.scrollTop = 0}
>
       Scroll up
</Button>
```

Hope that information helps you. Please let us know if we can help you with anything else.

Best,
Manu

**Comment by kzeman** [comment]
Thanks a lot 👍 ¨

Finally I used

                <Button
                    color="secondary"
                    style={{position: "absolute",right:"10px",bottom:"10px",zIndex:"9999",opacity:"0.5"}}
                    onClick={(e)=>this.refs.mainPanel.scrollTop = 0}
                >
                    &uarr;
                </Button>

Is it possible to show this button only if mainPanel is not scrolled to the top?

**Comment by einazare** [comment]
Hello @kzeman ,

Would it work to put an event listener on window scroll, and if it is 0, than add a property to the button to appear, else to not be rendered, or add an `display: none` property?

Best,
Manu

**Comment by kzeman** [comment]
A piece of code pls? :)

**Comment by einazare** [comment]
Hello again @kzeman ,

Here is the sample code:
```
componentDidUpdate(e) {
    if (e.history.location.pathname !== e.location.pathname) {
      this.refs.mainPanel.scrollTop = 0;
    }
  }
```

Best,
Manu

**Comment by kzeman** [comment]
> Hello again @kzeman ,
> Here is the sample code:
> 
> componentDidUpdate(e) {
>     if (e.history.location.pathname !== e.location.pathname) {
>       this.refs.mainPanel.scrollTop = 0;
>     }
>   }
> Best,
> Manu

Reply above belongs to another topic :)

**Comment by kzeman** [comment]
So again, can you please share a piece of code how to hide arrow button when the page is scrolled to the top?

**Comment by einazare** [comment]
Hello again @kzeman ,

I think this is fairly easy to do, i mean, the internet is full of such examples.
```
constructor(props) {
    super(props);
    this.state = {
      showButton: false
    };
}
componentDidMount() {
    this.refs.mainPanel.addEventListener('scroll', function(e) {
      console.log(this.refs.mainPanel.scrollTop);
      if(this.refs.mainPanel.scrollTop === 0 ){
        this.setState({showButton: false})
      } else if(this.refs.mainPanel.scrollTop > 99 ) {
        this.setState({showButton: true})
      }
    }.bind(this));
}
render(){
    return (
        ....
        <Button
            color="info"
            style={{position: "absolute",left:"auto",right:"0",zIndex:"9999",display: (this.state.showButton ? "block":"none")}}
            onClick={(e)=>this.refs.mainPanel.scrollTop = 0}
        >
            Scroll up
        </Button>
        ....
    );
}
```

Best,
Manu

**Comment by kzeman** [comment]
Great job!
